### ISSUE TITLE
Issues on latest version

### ISSUE THREAD

**Issue by communityreformed** [josephdadams/TallyArbiter-M5StickCListener#13]
I have followed the instructions to a T and yet I cannot get this to work on my MBP, I also tried on a fresh arduino install on a windows machine to no success. 
Here is the error on compiling

Arduino: 1.8.13 (Mac OS X), Board: "M5Stick-C, Default, 750000, None"

Traceback (most recent call last):
  File "esptool.py", line 57, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports.py", line 29, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_posix.py", line 31, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_osx.py", line 32, in <module>
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
Failed to execute script esptool
Multiple libraries were found for "WiFi.h"
 Used: /Users/matthewgrzybowski/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 255
/Applications/Arduino.app/Contents/Java/arduino-builder returned 255
Error compiling for board M5Stick-C.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by josephdadams** [comment]
Big Sur?

**Comment by josephdadams** [comment]
@communityreformed ?

**Comment by Rommert** [comment]
@josephdadams, I have got the same error. Can confirm: Big Sur, indeed.

**Comment by communityreformed** [comment]
Can confirm it was a big sur issue

**Comment by josephdadams** [comment]
Closing since it is not a TA issue.
