### ISSUE TITLE
error: 'class WiFiClientSecure' has no member named 'setInsecure'

### ISSUE THREAD

**Issue by Onfire7** [josephdadams/TallyArbiter-M5StickCListener#22]
Error compiling with a fresh install of Arduino and the libraries. Any help would be apreciated!

```
Arduino: 1.8.13 (Windows 10), Board: "M5Stick-C-Plus, Default, 750000, None"

C:\Users\live\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::loop()':

C:\Users\live\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:234:30: error: 'class WiFiClientSecure' has no member named 'setInsecure'

                 _client.ssl->setInsecure();

                              ^

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\live\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\1.0.7\libraries\WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

Error compiling for board M5Stick-C-Plus.
```

**Comment by techdude-777** [comment]
I had the same issue trying to compile the program.
What solved the issue for me, was tor instal version 2.3.4 of the WebSockets library instead of the newest 2.3.5.

Maybe this helps you.

@josephdadams: I really appreciate what you do and provide, simply such a great project and help! Many thanks!

**Comment by petervcook** [comment]
@techdude-777 's tip got me past one error but I came across another:
```
Traceback (most recent call last):
  File "/Users/peter/Library/Arduino15/packages/m5stack/tools/esptool_py/3.0.0/esptool.py", line 39, in <module>
    import serial
ImportError: No module named serial
Multiple libraries were found for "WiFi.h"
 Used: /Users/peter/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
Error compiling for board M5Stack-ATOM.
```
Any ideas?

**Comment by jordannwj** [comment]
Traceback (most recent call last):
  File "/Users/jordan/Library/Arduino15/packages/m5stack/tools/esptool_py/3.0.0/esptool.py", line 39, in <module>
    import serial
ImportError: No module named serial
exit status 1
Error compiling for board M5Stack-Core-ESP32.



Having this issue as well, hmmmm....

**Comment by petervcook** [comment]
@jordannwj @RaulDuke77 I was able to work my way past the same problem after I found this help thread:
https://community.m5stack.com/topic/2521/v1-0-6-of-board-manager-not-working-solved/11
The final post in that thread is a good guide
